Repository MIT-Emerging-Talent/ET6-foundations-group-24, pull requests merged in 2025-01, with the labels that each got.

#76 Numbers-Sort-Enhancement
  solutions/sort_numbers.py
  solutions/tests/test_sort_numbers.py
Labels: enhancement

#66 check anagram done and ready for review
  solutions/check_anagram.py
  solutions/tests/test_check_anagram.py
Labels: Challenge

#52 Sort colors
  solutions/sort_colors.py
  solutions/tests/test_sort_colors.py
Labels: Challenge

#55 Factorial calculator
  .vscode/settings.json
  =
  solutions/factorial_calculator.py
  solutions/tests/test_factorial_calculator.py
Labels: Challenge

#78 solutions and tests readme
  .markdownlint.yml
  solutions/README.md
  solutions/tests/README.md
Labels: documentation

#65 Ascii code
  solutions/ascii_code.py
  solutions/tests/test_ascii_code.py
Labels: Challenge

#67 Intersection of two
  solutions/intersection_of_two.py
  solutions/tests/test_intersection_of_two.py
Labels: Challenge

#85 Update the function's docstring
  solutions/intersection_of_two.py
Labels: enhancement

#54 Sum range
  .vscode/settings.json
  solutions/sum_range.py
  solutions/tests/test_sum_range.py
Labels: Challenge

#47 28 is leap year
  solutions/is_leap_year.py
  solutions/tests/test_is_leap_year.py
Labels: Challenge

#46 27 binary to decimal converter
  solutions/binary_to_decimal.py
  solutions/tests/test_binary_to_decimal.py
Labels: Challenge

#74 Count digits
  solutions/count_digits.py
  solutions/tests/test_count_digits.py
Labels: Challenge

#86 23 sort colors
  solutions/sort_colors.py
  solutions/tests/test_sort_colors.py
Labels: Challenge

#94 Robel notes included
  notes/frst_meeting_note.md
Labels: documentation

#99 Update communication.md
  collaboration/communication.md
Labels: documentation

#100 Repo readme
  .vscode/settings.json
  README.md
Labels: enhancement

#102 Retrospective
  collaboration/retrospective.md
Labels: documentation

#104 Changes made by Mr. Evan.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
